# Generated by Django 5.2.4 on 2025-07-29 05:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportrecord',
            name='record_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='记录日期'),
        ),
    ]
