# Generated by Django 5.2.4 on 2025-07-29 05:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sportrecord_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='record_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='记录日期'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='calories_calculated',
            field=models.FloatField(blank=True, null=True, verbose_name='计算卡路里(大卡)'),
        ),
    ]
