# Generated by Django 5.2.4 on 2025-08-05 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_meal_record_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHealthGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_sleep_duration', models.FloatField(blank=True, help_text='例如: 7.5', null=True, verbose_name='目标睡眠时长(小时)')),
                ('target_sport_duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='目标运动时长(分钟)')),
                ('target_sport_calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='目标运动消耗热量(大卡)')),
                ('target_diet_calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='目标饮食摄入热量(大卡)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_goal', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
        ),
    ]
