# Generated by Django 5.2.4 on 2025-08-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userhealthgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='产品代码'),
        ),
    ]
