# Generated by Django 5.2.4 on 2025-08-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fooditem_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='carbohydrates',
            field=models.FloatField(blank=True, null=True, verbose_name='碳水化合物(克)'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='fat',
            field=models.FloatField(blank=True, null=True, verbose_name='脂肪(克)'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='protein',
            field=models.FloatField(blank=True, null=True, verbose_name='蛋白质(克)'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='食物名称'),
        ),
    ]
